#!/usr/bin/env python3
"""Add DSA questions from GFG Top 100 list to questions.json."""
import json, os

QUESTIONS_JSON = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'questions.json')

questions = [
    # === ARRAY (9) ===
    {"topic":"DSA","difficulty":"Easy","question":"Pair with the given sum: Given an array of integers, check if there exists a pair with a given target sum.","answer":"Use a hash set to store seen elements. For each element, check if target - element exists in the set. Time: O(n), Space: O(n). Also known as the Two Sum problem."},
    {"topic":"DSA","difficulty":"Easy","question":"Best Time to Buy and Sell Stock: Given stock prices on different days, find the maximum profit possible by buying and selling at most once.","answer":"Track the minimum price seen so far. For each price, compute potential profit = price - minSoFar and update max profit. Time: O(n), Space: O(1). The key insight is to buy low and sell high in a single pass."},
    {"topic":"DSA","difficulty":"Medium","question":"Product of Array Except Self: Given an array, return an array where each element is the product of all elements except itself, without using division.","answer":"Compute prefix products from left to right and suffix products from right to left. Then multiply prefix[i-1] * suffix[i+1] for each position. Time: O(n), Space: O(1) excluding output. Can be done in two passes with a single output array."},
    {"topic":"DSA","difficulty":"Easy","question":"Maximum Subarray (Kadane's Algorithm): Find the contiguous subarray with the largest sum.","answer":"Use Kadane's algorithm: maintain current sum and max sum. For each element, decide whether to start a new subarray (element alone) or extend the existing one (current + element). Time: O(n), Space: O(1). Classic example of dynamic programming with O(1) space."},
    {"topic":"DSA","difficulty":"Medium","question":"Container With Most Water: Given heights of vertical lines, find two lines that together with the x-axis form a container holding the most water.","answer":"Use two pointers at both ends. The area is min(height[l], height[r]) * (r-l). Move the pointer with the smaller height inward. Time: O(n), Space: O(1). The greedy approach works because moving the taller line can only decrease area."},
    {"topic":"DSA","difficulty":"Medium","question":"Factorial of a large number: Compute factorial of a large number (e.g., 100) where the result exceeds standard integer limits.","answer":"Use an array to store digits of the result. Multiply each digit by the next number, handle carry like manual multiplication. Time: O(n * digits), Space: O(digits). For factorial(100), the result has 158 digits."},
    {"topic":"DSA","difficulty":"Hard","question":"Trapping Rain Water: Given elevation heights, compute how much water can be trapped after rain.","answer":"Use two pointers from both ends tracking leftMax and rightMax. At each step, process the smaller height side: if current > max, update max; else add max - current to total. Time: O(n), Space: O(1). Alternative: prefix/suffix max arrays for O(n) space."},
    {"topic":"DSA","difficulty":"Medium","question":"Insert and Merge Intervals: Insert a new interval into a sorted list of non-overlapping intervals and merge if necessary.","answer":"Iterate through intervals, adding those ending before the new interval starts. Merge overlapping intervals by adjusting start and end. Add remaining intervals after. Time: O(n), Space: O(n). Handle cases where new interval is before all, after all, or overlaps multiple intervals."},
    {"topic":"DSA","difficulty":"Medium","question":"Merge Intervals: Given a collection of intervals, merge all overlapping intervals.","answer":"Sort intervals by start time. Iterate: if current interval overlaps with the last merged interval, merge them (update end to max of both ends); otherwise add it as a new interval. Time: O(n log n) due to sorting, Space: O(n)."},

    # === MATRIX (3) ===
    {"topic":"DSA","difficulty":"Medium","question":"Spiral Matrix: Given an m x n matrix, return all elements in spiral order.","answer":"Use four boundaries (top, bottom, left, right). Traverse right across top row, then down right column, then left across bottom row, then up left column, updating boundaries each time. Time: O(m*n), Space: O(1) excluding output. Handle edge cases of single row/column matrices."},
    {"topic":"DSA","difficulty":"Easy","question":"Transpose of a matrix: Given a matrix, find its transpose (rows become columns).","answer":"For a square matrix, swap elements across the diagonal: matrix[i][j] with matrix[j][i]. For rectangular, create a new matrix with dimensions swapped and copy values. Time: O(m*n), Space: O(1) in-place for square, O(m*n) for rectangular."},
    {"topic":"DSA","difficulty":"Medium","question":"Word Search: Given a 2D grid of characters and a word, find if the word exists in the grid (adjacent cells horizontally or vertically).","answer":"Use DFS with backtracking from each matching starting cell. Mark visited cells (temporarily change char or use visited set). Explore all 4 directions. Time: O(m*n*4^L) where L is word length. Prune by checking character matches first."},

    # === STRING (7) ===
    {"topic":"DSA","difficulty":"Medium","question":"Longest Substring Without Repeating Characters: Find the length of the longest substring without repeating characters.","answer":"Use sliding window with two pointers and a hash set/map. Expand the right pointer, if a duplicate is found, shrink from the left until the duplicate is removed. Time: O(n), Space: O(min(m,n)) where m is character set size. The map approach stores character positions for O(1) skips."},
    {"topic":"DSA","difficulty":"Medium","question":"Longest Repeating Character Replacement: Given a string and k replacements, find the longest substring with the same character after at most k changes.","answer":"Use sliding window tracking character frequencies. Maintain max frequency count in the window. A window is valid if (windowSize - maxFreq) <= k. Expand right, when invalid shrink left. Time: O(n), Space: O(26) for uppercase letters."},
    {"topic":"DSA","difficulty":"Hard","question":"Smallest window containing all characters: Given two strings s and p, find the smallest substring in s that contains all characters of p.","answer":"Use sliding window with two frequency maps (or one map with counter). Track required and have counts. Expand right pointer, when all chars matched, shrink from left to minimize window. Time: O(n), Space: O(m) where m is character set."},
    {"topic":"DSA","difficulty":"Medium","question":"Print all anagrams together: Given a list of strings, group anagrams together.","answer":"Use a hash map where key is the sorted version of each string (or character count signature). Iterate through strings, normalize each by sorting, and add to the corresponding group. Time: O(n*k*log k) where k is max string length. Space: O(n*k)."},
    {"topic":"DSA","difficulty":"Easy","question":"Sentence Palindrome: Check if a sentence is a palindrome ignoring spaces, punctuation, and case.","answer":"Use two pointers from both ends, skipping non-alphanumeric characters. Compare characters after converting to same case. Time: O(n), Space: O(1). Handle empty string and single character cases."},
    {"topic":"DSA","difficulty":"Medium","question":"Longest Palindromic Substring: Find the longest palindromic substring in a given string.","answer":"Expand around center: each character and each gap between characters can be the center of a palindrome. Expand outward while both sides match. Track the longest. Time: O(n^2), Space: O(1). Manacher's algorithm achieves O(n) but is complex."},
    {"topic":"DSA","difficulty":"Medium","question":"Palindromic Substrings: Count total palindromic substrings in a string.","answer":"Use expand around center approach. Each of the 2n-1 centers (n single chars + n-1 gaps) is expanded to count palindromes. Time: O(n^2), Space: O(1). Can also be solved with DP where dp[i][j] indicates if s[i..j] is a palindrome."},

    # === SEARCHING & SORTING (9) ===
    {"topic":"DSA","difficulty":"Medium","question":"Search in Rotated Sorted Array: Given a rotated sorted array, find a target value.","answer":"Modified binary search. Find which half is sorted by comparing mid with left. If left half is sorted (arr[left] <= arr[mid]), check if target is in that range; otherwise search the right half. Time: O(log n), Space: O(1). Handle duplicates separately."},
    {"topic":"DSA","difficulty":"Easy","question":"Peak Element: Find a peak element in an array (element greater than its neighbors).","answer":"Use binary search. If mid element is greater than its neighbors, return it. If left neighbor is greater, search left half; otherwise search right half. Time: O(log n), Space: O(1). There can be multiple peaks; this finds any one."},
    {"topic":"DSA","difficulty":"Hard","question":"K-th element of two sorted arrays: Find the k-th smallest element in the union of two sorted arrays.","answer":"Binary search on the smaller array. Partition both arrays such that left partition has k elements. Check if maxLeftA <= minRightB and maxLeftB <= minRightA. Adjust partition using binary search. Time: O(log(min(m,n))), Space: O(1)."},
    {"topic":"DSA","difficulty":"Hard","question":"Allocate Minimum Pages: Given books with pages and m students, allocate books to minimize the maximum pages a student reads.","answer":"Binary search on the answer (max pages). For a given mid, check if we can allocate books such that no student reads more than mid pages. Low = max pages of any book, high = sum of all pages. Time: O(n*log(sum)), Space: O(1)."},
    {"topic":"DSA","difficulty":"Easy","question":"Kth Missing Positive Number: Given a sorted array of distinct positive integers, find the k-th missing positive number.","answer":"Use binary search. The number of missing elements before index i is arr[i] - (i+1). Find the position where missing count crosses k. Then answer = k + index. Time: O(log n), Space: O(1)."},
    {"topic":"DSA","difficulty":"Easy","question":"Sort 0s, 1s and 2s (Dutch National Flag): Given an array of 0s, 1s, and 2s, sort them in-place.","answer":"Use three pointers (low, mid, high). Mid pointer traverses: if arr[mid]==0, swap with low, increment both. If arr[mid]==1, increment mid. If arr[mid]==2, swap with high, decrement high. Time: O(n), Space: O(1)."},
    {"topic":"DSA","difficulty":"Hard","question":"Count Inversions: Given an array, count the number of inversions (pairs where i<j and arr[i]>arr[j]).","answer":"Use modified merge sort. During merge, when an element from the right half is placed before elements from the left half, count inversions = mid - leftIndex + 1. Time: O(n log n), Space: O(n). Brute force is O(n^2)."},
    {"topic":"DSA","difficulty":"Hard","question":"Merge two sorted arrays without extra space: Given two sorted arrays, merge them in-place without using extra space.","answer":"Use the Gap method (Shell sort inspired). Start with gap = ceil((m+n)/2), compare and swap elements at distance gap, reduce gap by half. Alternative: insert elements of second array into first using insertion sort. Time: O((m+n)*log(m+n)), Space: O(1)."},
    {"topic":"DSA","difficulty":"Easy","question":"Chocolate Distribution Problem: Given packets of chocolates, distribute to m students so that difference between max and min chocolates a student gets is minimized.","answer":"Sort the array. Use sliding window of size m: for each window, compute max-min and track the minimum difference. Time: O(n log n) due to sorting, Space: O(1)."},

    # === HASHING (4) ===
    {"topic":"DSA","difficulty":"Easy","question":"Print all pairs with given sum: Find all pairs in an array that sum to a target value.","answer":"Use a hash map counting element frequencies. For each element, check if target-element exists in the map. Handle duplicates properly by decrementing counts. Time: O(n), Space: O(n)."},
    {"topic":"DSA","difficulty":"Medium","question":"Longest Subsequence with Adjacent Difference of 0 or 1: Find the longest subsequence where adjacent elements differ by at most 1.","answer":"Use hash map for dynamic programming where dp[x] is the longest subsequence ending with value x. For each element, dp[x] = max(dp[x-1], dp[x], dp[x+1]) + 1. Time: O(n), Space: O(n)."},
    {"topic":"DSA","difficulty":"Medium","question":"Longest Consecutive Sequence: Given an unsorted array, find the length of the longest consecutive elements sequence.","answer":"Use a hash set for O(1) lookups. Iterate through elements, only start counting when the previous number (num-1) is not in the set. Then count consecutive numbers. Time: O(n), Space: O(n). Each element is visited at most twice."},
    {"topic":"DSA","difficulty":"Medium","question":"Count Subarrays with given XOR: Count subarrays whose XOR equals a target value.","answer":"Use prefix XOR and hash map. Prefix XOR up to i is XOR of elements from 0 to i. If prefixXOR ^ target has been seen before, those subarrays end at i with the target XOR. Time: O(n), Space: O(n)."},

    # === LINKED LIST (8) ===
    {"topic":"DSA","difficulty":"Easy","question":"Reverse a Linked List: Reverse a singly linked list.","answer":"Use three pointers (prev, current, next). Iteratively reverse each node's next pointer. Base case: empty or single node. Time: O(n), Space: O(1). Can also be done recursively with O(n) call stack space."},
    {"topic":"DSA","difficulty":"Easy","question":"Detect Cycle in a Linked List: Determine if a linked list has a cycle.","answer":"Use Floyd's Cycle Detection (fast and slow pointers). Fast moves 2 steps, slow moves 1 step. If they meet, there is a cycle. Time: O(n), Space: O(1). Alternative: use hash set of visited nodes requiring O(n) space."},
    {"topic":"DSA","difficulty":"Easy","question":"Merge Two Sorted Lists: Merge two sorted linked lists into one sorted list.","answer":"Use a dummy head node. Compare heads of both lists, attach the smaller node to result, advance the pointer. When one list is exhausted, attach the remaining nodes. Time: O(n+m), Space: O(1). Recursive solution also possible."},
    {"topic":"DSA","difficulty":"Hard","question":"Merge K Sorted Lists: Merge k sorted linked lists into one sorted list.","answer":"Use a min-heap (priority queue) of ListNode heads. Extract minimum, add to result, push the next node from that list. Time: O(n*log k) where n is total nodes, k is number of lists. Space: O(k) for the heap."},
    {"topic":"DSA","difficulty":"Medium","question":"Remove Nth Node From End Of List: Remove the n-th node from the end of a linked list in one pass.","answer":"Use two pointers with a gap of n nodes. Move the fast pointer n steps ahead, then move both until fast reaches the end. Slow pointer is at the node before the one to remove. Time: O(n), Space: O(1). Handle edge case of removing head."},
    {"topic":"DSA","difficulty":"Medium","question":"Reorder List: Reorder a linked list L0->L1->...->Ln-1->Ln to L0->Ln->L1->Ln-1->L2->...","answer":"Find the middle (slow/fast), reverse the second half, then merge the two halves alternately. Time: O(n), Space: O(1). The reversal and merge steps each take O(n/2)."},
    {"topic":"DSA","difficulty":"Medium","question":"Add 1 to a number represented as linked list: Given a linked list representing a number, add 1 to it.","answer":"Reverse the list, add 1 with carry propagation, reverse back. Alternative: use recursion to process from last node, propagating carry. Time: O(n), Space: O(1) iterative or O(n) recursive stack."},
    {"topic":"DSA","difficulty":"Hard","question":"Clone a Linked List (with next and random/arbitrary pointer): Deep clone a linked list where each node has a next pointer and a random pointer.","answer":"Interweave: insert cloned nodes between original nodes, set random pointers of clones (clone.random = original.random.next), then separate the lists. Time: O(n), Space: O(1). Alternative uses hash map mapping original to clone nodes."},

    # === STACK, QUEUE & DEQUE (9) ===
    {"topic":"DSA","difficulty":"Medium","question":"Infix to Postfix expression: Convert an infix expression to postfix notation.","answer":"Use a stack for operators. Scan left to right: output operands directly. For operators, pop from stack while higher or equal precedence (left-associative), then push current. Handle parentheses: push '(' and pop until '(' on ')'. Time: O(n), Space: O(n)."},
    {"topic":"DSA","difficulty":"Medium","question":"Next Greater Element: For each element in an array, find the next greater element to its right.","answer":"Use a monotonic decreasing stack. Iterate from left to right: while current > stack top, pop and set result for that index to current. Push current index onto stack. Time: O(n), Space: O(n). Remaining elements in stack have no greater element (-1)."},
    {"topic":"DSA","difficulty":"Hard","question":"Largest Area in a Histogram: Find the largest rectangular area in a histogram.","answer":"Use a stack storing indices of increasing heights. When a shorter bar is encountered, pop taller bars and compute area using the popped height and width extending from previous smaller bar to current index. Time: O(n), Space: O(n)."},
    {"topic":"DSA","difficulty":"Easy","question":"Delete middle element of a stack: Delete the middle element of a stack without using any additional data structure.","answer":"Use recursion. Pop elements one by one, recursively call for remaining stack, push back elements except the middle one. Track depth with a counter. Time: O(n), Space: O(n) for recursion stack."},
    {"topic":"DSA","difficulty":"Hard","question":"Length of the longest valid substring of parentheses: Find the length of the longest valid parentheses substring.","answer":"Use a stack storing indices. Push -1 initially. For '(' push index. For ')' pop and compute length = current index - stack top. Time: O(n), Space: O(n). Alternative O(1) space using two counters scanning left to right and right to left."},
    {"topic":"DSA","difficulty":"Hard","question":"Sum of Max of Subarrays: Sum of maximum elements of all subarrays of an array.","answer":"For each element, find its contribution as maximum in how many subarrays. Use a monotonic stack to find the nearest greater element on left and right. Contribution = arr[i] * (i-left) * (right-i). Time: O(n), Space: O(n)."},
    {"topic":"DSA","difficulty":"Medium","question":"Next Greater Element in a Circular Array: Find the next greater element for each element in a circular array.","answer":"Extend the array conceptually by traversing 2*n elements. Use a monotonic decreasing stack. For i from 0 to 2n-1, process arr[i%n] while stack top < arr[i%n], set result for the popped index. Time: O(n), Space: O(n)."},
    {"topic":"DSA","difficulty":"Hard","question":"Longest Bounded-Difference Subarray: Longest subarray where absolute difference between any two elements is <= X.","answer":"Use two deques (min and max) for sliding window. Maintain increasing min-deque and decreasing max-deque. Expand right pointer, when window violates condition (max-min > X), shrink left. Time: O(n), Space: O(n)."},
    {"topic":"DSA","difficulty":"Hard","question":"K Sized Subarray Maximum (Sliding Window Maximum): Find maximum in every subarray of size k.","answer":"Use a deque storing indices of elements in decreasing order. For each window: remove out-of-range indices from front, remove smaller elements from back before adding new element, front is max for current window. Time: O(n), Space: O(k)."},

    # === TREE (12) ===
    {"topic":"DSA","difficulty":"Easy","question":"Maximum Depth of Binary Tree: Find the maximum depth (height) of a binary tree.","answer":"Recursively compute maxDepth = 1 + max(maxDepth(left), maxDepth(right)). Base case: null node has depth 0. Time: O(n), Space: O(h) where h is height. Iterative DFS/BFS also possible."},
    {"topic":"DSA","difficulty":"Easy","question":"Check for Mirror Trees: Check if two trees are mirror images of each other.","answer":"Recursively check if root1.left mirrors root2.right and root1.right mirrors root2.left. Both nodes must have same value. Base case: both null returns true, one null returns false. Time: O(n), Space: O(h)."},
    {"topic":"DSA","difficulty":"Easy","question":"Invert/Flip Binary Tree: Invert a binary tree (mirror it).","answer":"Recursively swap left and right children of each node. Post-order: invert left subtree, invert right subtree, then swap. Time: O(n), Space: O(h). Iterative BFS with queue also works."},
    {"topic":"DSA","difficulty":"Hard","question":"Binary Tree Maximum Path Sum: Find the maximum path sum in a binary tree (path can start and end at any node).","answer":"Post-order traversal: compute max gain from each node = node.val + max(leftGain, rightGain, 0). Update global max with node.val + leftGain + rightGain. Return max gain upward. Time: O(n), Space: O(h)."},
    {"topic":"DSA","difficulty":"Medium","question":"Binary Tree Level Order Traversal: Return level-order traversal of a binary tree.","answer":"Use a queue for BFS. Process level by level: for each level, get the current queue size, dequeue that many nodes, add their values to the current level list, enqueue children. Time: O(n), Space: O(n) for queue."},
    {"topic":"DSA","difficulty":"Hard","question":"Serialize and Deserialize Binary Tree: Convert a binary tree to a string and back.","answer":"Use pre-order traversal with a sentinel (e.g., 'null') for null nodes. Serialize: concatenate node values with separators. Deserialize: use a queue of values, recursively build tree. Time: O(n), Space: O(n). BFS level-order also works."},
    {"topic":"DSA","difficulty":"Easy","question":"Subtree of Another Tree: Check if tree t is a subtree of tree s.","answer":"For each node in s, check if the tree rooted at that node is identical to t. Use a helper that checks tree equality recursively. Optimize by serializing both trees and using string matching (KMP). Time: O(s*t) naive, O(s+t) with KMP."},
    {"topic":"DSA","difficulty":"Medium","question":"Construct Binary Tree from Preorder and Inorder Traversal: Build a binary tree given its preorder and inorder traversals.","answer":"First element of preorder is root. Find root index in inorder. Elements left of root in inorder form left subtree, right form right subtree. Recursively build using indices. Time: O(n), Space: O(n) for hash map of inorder indices."},
    {"topic":"DSA","difficulty":"Medium","question":"Validate Binary Search Tree: Check if a binary tree is a valid BST.","answer":"In-order traversal should produce strictly increasing values. Alternatively, pass down valid range (min, max) for each node: left child must be < root, right child must be > root. Time: O(n), Space: O(h)."},
    {"topic":"DSA","difficulty":"Medium","question":"Kth Smallest Element in a BST: Find the k-th smallest element in a BST.","answer":"Perform in-order traversal (gives sorted order). Use a counter or stack-based iterative traversal. When counter reaches k, return the current node's value. Time: O(h + k), Space: O(h). Follow-up: Augment each node with left subtree size for O(log n) queries."},
    {"topic":"DSA","difficulty":"Medium","question":"Lowest Common Ancestor of BST: Find the lowest common ancestor of two nodes in a BST.","answer":"Traverse from root. If both nodes are smaller than current, go left. If both larger, go right. Otherwise, current node is the LCA (one is on left, other on right, or current equals one of them). Time: O(h), Space: O(1) iterative."},
    {"topic":"DSA","difficulty":"Medium","question":"Implement Trie (Prefix Tree): Implement a trie with insert, search, and startsWith operations.","answer":"Each node has an array/map of children and a boolean isEndOfWord. Insert: traverse/create nodes for each character, mark last. Search: traverse characters, check isEndOfWord at last node. StartsWith: traverse characters, check if path exists. Time: O(L) per operation where L is word length."},

    # === HEAP (4) ===
    {"topic":"DSA","difficulty":"Medium","question":"Top K Frequent Elements: Given an array, find the k most frequent elements.","answer":"Count frequencies using hash map. Use a min-heap of size k: push (frequency, element) pairs, if heap size > k, pop smallest. Alternatively, use bucket sort on frequencies. Time: O(n log k) with heap, O(n) with bucket sort. Space: O(n)."},
    {"topic":"DSA","difficulty":"Hard","question":"Find Median from Data Stream: Design a data structure that supports adding numbers and finding the median.","answer":"Use two heaps: a max-heap for the left half and a min-heap for the right half. Maintain size difference <= 1. Median is max-heap's top (odd) or average of both tops (even). Time: O(log n) per add, O(1) for find. Space: O(n)."},
    {"topic":"DSA","difficulty":"Medium","question":"Largest triplet product in a stream: Given a stream of numbers, find the largest product of three numbers at each insertion.","answer":"Maintain three largest and two smallest numbers (for negative * negative * positive). After each insertion, the max product is max(largest * second * third, largest * smallest * secondSmallest). Time: O(1) per insertion, Space: O(1)."},
    {"topic":"DSA","difficulty":"Easy","question":"Connect n Ropes with minimum cost: Given rope lengths, repeatedly connect two ropes at cost equal to their sum, minimize total cost.","answer":"Use a min-heap. Extract the two smallest ropes, connect them (cost += sum), push the sum back. Repeat until one rope remains. Time: O(n log n), Space: O(n). This is Huffman Coding's greedy approach."},

    # === GRAPH (12) ===
    {"topic":"DSA","difficulty":"Medium","question":"Clone Graph: Deep clone an undirected graph (each node has neighbors).","answer":"Use DFS or BFS with a hash map mapping original nodes to cloned nodes. When visiting a node, create its clone if not already mapped. Recursively/clone neighbors and add them to the clone's neighbors list. Time: O(V+E), Space: O(V)."},
    {"topic":"DSA","difficulty":"Medium","question":"Course Schedule: Determine if you can finish all courses given prerequisites. Equivalent to detecting cycle in a directed graph.","answer":"Build adjacency list and indegree array. Use Kahn's algorithm (BFS with queue of zero indegree nodes). If all nodes are processed, no cycle exists. Alternatively, use DFS with visited states (0=unvisited, 1=visiting, 2=visited). Time: O(V+E), Space: O(V+E)."},
    {"topic":"DSA","difficulty":"Medium","question":"Pacific Atlantic Water Flow: Find cells where water can flow to both Pacific (top/left) and Atlantic (bottom/right) oceans.","answer":"Start DFS/BFS from border cells that touch each ocean. Track which cells can reach Pacific and which can reach Atlantic. Cells in both sets are the answer. Time: O(m*n), Space: O(m*n)."},
    {"topic":"DSA","difficulty":"Medium","question":"Number of Islands: Count the number of islands in a 2D grid (1=land, 0=water, connected horizontally/vertically).","answer":"DFS from each unvisited land cell, marking connected land as visited (change to 0 or use visited set). Each DFS initiation increments the island count. Time: O(m*n), Space: O(m*n) worst case recursion. BFS also works."},
    {"topic":"DSA","difficulty":"Medium","question":"Snake and Ladder Problem: Find the minimum moves in a snake and ladder board game.","answer":"Model as a graph of 100 cells. Use BFS from cell 1. Roll dice (1-6) from each cell, follow snake/ladder if present. Track visited cells. Time: O(n) where n is board size, Space: O(n)."},
    {"topic":"DSA","difficulty":"Medium","question":"Detect Cycle in a Directed Graph: Check if a directed graph has a cycle.","answer":"Use DFS with three states: 0=unvisited, 1=in current path (visiting), 2=processed. If we encounter a node in state 1, a cycle exists. Alternative: Kahn's algorithm (topological sort with BFS). Time: O(V+E), Space: O(V)."},
    {"topic":"DSA","difficulty":"Hard","question":"Bridges in a Graph: Find all bridges (edges whose removal increases connected components) in an undirected graph.","answer":"Use Tarjan's algorithm with DFS. Track discovery time and low-link values for each node. An edge (u,v) is a bridge if low[v] > disc[u] (no back edge from v's subtree to u or above). Time: O(V+E), Space: O(V)."},
    {"topic":"DSA","difficulty":"Medium","question":"Check for Bipartite Graph: Determine if a graph can be colored with 2 colors such that adjacent nodes have different colors.","answer":"Use BFS/DFS with color array (-1 uncolored). For each uncolored node, assign color 0, then color neighbors with 1, recursively. If a neighbor has the same color, graph is not bipartite. Time: O(V+E), Space: O(V)."},
    {"topic":"DSA","difficulty":"Medium","question":"Largest region in Boolean Matrix: Find the largest connected region (8-directional) of 1s in a binary matrix.","answer":"DFS from each 1 cell, counting connected 1s. Mark visited cells. Check all 8 directions. Track maximum region size. Time: O(m*n), Space: O(m*n) worst case recursion stack."},
    {"topic":"DSA","difficulty":"Medium","question":"Flood fill Algorithm: Given a starting pixel, change its color and all connected same-colored pixels.","answer":"Use DFS or BFS. If the starting pixel already has the target color, return. Recurse in 4 directions for pixels with the same original color. Time: O(m*n), Space: O(m*n) worst case."},
    {"topic":"DSA","difficulty":"Hard","question":"Strongly Connected Components: Find SCCs in a directed graph (Kosaraju's or Tarjan's algorithm).","answer":"Kosaraju's: 1) DFS to get finishing order stack. 2) Reverse the graph. 3) Process nodes in stack order, each DFS gives one SCC. Time: O(V+E), Space: O(V). Tarjan's uses single DFS with low-link values."},
    {"topic":"DSA","difficulty":"Medium","question":"Topological Sorting: Order nodes in a DAG such that for every edge u->v, u comes before v.","answer":"Use Kahn's algorithm (BFS with indegree array). Add nodes with zero indegree to queue. Remove each node, decrement neighbors' indegree, add newly zero-indegree nodes. Or use DFS post-order reversal. Time: O(V+E), Space: O(V)."},

    # === DYNAMIC PROGRAMMING & GREEDY (20) ===
    {"topic":"DSA","difficulty":"Easy","question":"Count ways to reach the n-th stair: Count distinct ways to reach the top climbing 1 or 2 steps at a time.","answer":"This is Fibonacci: ways(n) = ways(n-1) + ways(n-2). Base: ways(1)=1, ways(2)=2. Use DP with O(n) time or matrix exponentiation for O(log n). Space can be O(1) with two variables."},
    {"topic":"DSA","difficulty":"Medium","question":"Coin Change: Find the minimum number of coins needed to make a target amount using given coin denominations.","answer":"DP: dp[i] = minimum coins for amount i. For each coin, dp[i] = min(dp[i], dp[i-coin] + 1). Initialize dp[0]=0, others = infinity. Time: O(n*amount), Space: O(amount). Greedy doesn't work for arbitrary denominations."},
    {"topic":"DSA","difficulty":"Medium","question":"0/1 Knapsack Problem: Given item weights and values, maximize value with weight capacity W, each item taken at most once.","answer":"DP: dp[i][w] = max value using first i items with capacity w. Transition: skip item or take it (value[i] + dp[i-1][w-weight[i]]). Optimize to 1D array iterating capacity backwards. Time: O(n*W), Space: O(W)."},
    {"topic":"DSA","difficulty":"Medium","question":"Longest Increasing Subsequence: Find the length of the longest increasing subsequence.","answer":"DP O(n^2): dp[i] = 1 + max(dp[j]) for j<i and arr[j]<arr[i]. Optimal O(n log n): maintain tails array where tails[i] is smallest possible tail of increasing subsequence of length i+1. Binary search to place each element."},
    {"topic":"DSA","difficulty":"Medium","question":"Longest Common Subsequence: Find the length of the longest subsequence common to two strings.","answer":"DP: dp[i][j] = LCS of first i chars of s1 and first j chars of s2. If s1[i-1]==s2[j-1], dp[i][j]=1+dp[i-1][j-1]. Else dp[i][j]=max(dp[i-1][j], dp[i][j-1]). Time: O(m*n), Space: O(min(m,n)) optimized."},
    {"topic":"DSA","difficulty":"Medium","question":"Word Break Problem: Given a string and a dictionary, determine if the string can be segmented into dictionary words.","answer":"DP: dp[i] = true if s[0..i] can be segmented. For each j < i, if dp[j] is true and s[j..i] is in dictionary, dp[i] = true. Time: O(n^2) or O(n * maxWordLen). Space: O(n). Use Trie for faster lookups."},
    {"topic":"DSA","difficulty":"Hard","question":"Dice Throw: Count ways to get a target sum by throwing n dice with m faces each.","answer":"DP: dp[i][j] = ways to get sum j using i dice. dp[i][j] = sum(dp[i-1][j-k]) for k=1 to m where j>=k. Time: O(n*m*sum), Space: O(sum) optimized. Base: dp[0][0]=1."},
    {"topic":"DSA","difficulty":"Hard","question":"Egg Dropping Puzzle: Find the minimum number of attempts to find the critical floor in a building with k eggs and n floors.","answer":"DP: dp[e][f] = min attempts with e eggs and f floors. dp[e][f] = 1 + min(max(dp[e-1][x-1], dp[e][f-x])) for x=1..f. Binary search optimization for the optimal x. Time: O(k*n*log n) optimized, Space: O(k*n)."},
    {"topic":"DSA","difficulty":"Hard","question":"Matrix Chain Multiplication: Find the minimum cost to multiply a chain of matrices.","answer":"DP: dp[i][j] = min cost to multiply matrices i..j. dp[i][j] = min(dp[i][k] + dp[k+1][j] + dims[i-1]*dims[k]*dims[j]) for k=i..j-1. Time: O(n^3), Space: O(n^2). Can be optimized with Knuth optimization for certain cost functions."},
    {"topic":"DSA","difficulty":"Medium","question":"Combination Sum: Find all unique combinations where numbers sum to a target (each number can be used unlimited times).","answer":"Use backtracking/DFS. Sort candidates first. At each step, include current candidate or skip it. Prune when sum exceeds target. Use i (not i+1) in recursive call to reuse same element. Time: O(2^(target/min)), Space: O(target/min)."},
    {"topic":"DSA","difficulty":"Medium","question":"Subset Sum Problem: Determine if there is a subset with sum equal to a given target.","answer":"DP: dp[i][j] = true if sum j possible using first i elements. dp[i][j] = dp[i-1][j] OR dp[i-1][j-arr[i-1]]. Optimize to 1D boolean array. Time: O(n*target), Space: O(target). Base: dp[0][0]=true."},
    {"topic":"DSA","difficulty":"Easy","question":"Maximum possible stolen value (House Robber): Given house values, find max sum without robbing adjacent houses.","answer":"DP: dp[i] = max value up to house i. dp[i] = max(dp[i-1], dp[i-2] + nums[i]). Base: dp[0]=nums[0], dp[1]=max(nums[0], nums[1]). Optimize to O(1) space with two variables. Time: O(n)."},
    {"topic":"DSA","difficulty":"Medium","question":"Count Possible Decodings of a given Digit Sequence: Count ways to decode a digit string (A=1, B=2, ..., Z=26).","answer":"DP: dp[i] = ways to decode first i chars. dp[i] = dp[i-1] (if s[i-1]!='0') + dp[i-2] (if s[i-2..i-1] is 10-26). Time: O(n), Space: O(1). Handle leading zeros. Similar to Fibonacci with constraints."},
    {"topic":"DSA","difficulty":"Medium","question":"Unique paths in a Grid with Obstacles: Count paths from top-left to bottom-right avoiding obstacles (move only right/down).","answer":"DP: dp[i][j] = ways to reach cell (i,j). If cell has obstacle, dp[i][j]=0. Else dp[i][j] = dp[i-1][j] + dp[i][j-1]. Use 1D array for space optimization. Time: O(m*n), Space: O(n)."},
    {"topic":"DSA","difficulty":"Medium","question":"Jump Game: Determine if you can reach the last index, where each element is the max jump length from that position.","answer":"Greedy: track the farthest reachable index. For each position, if it's beyond the farthest, return false. Update farthest = max(farthest, i + nums[i]). Time: O(n), Space: O(1). DP approach also works but is O(n^2)."},
    {"topic":"DSA","difficulty":"Medium","question":"Cutting a Rod: Given a rod of length n and prices for each length, find the maximum profit by cutting and selling pieces.","answer":"DP: dp[i] = max profit for rod of length i. For each cut j=1..i, dp[i] = max(dp[i], price[j-1] + dp[i-j]). Time: O(n^2), Space: O(n). Unbounded knapsack variant."},
    {"topic":"DSA","difficulty":"Medium","question":"Maximum Product Cutting: Given a rope of length n, cut it into parts to maximize the product of part lengths.","answer":"DP: dp[i] = max product for rope length i. For cut j=1..i-1, dp[i] = max(dp[i], j * (i-j), j * dp[i-j]). The optimal strategy: cut into lengths of 3 as much as possible (when n>4). Time: O(n^2) or O(1) with math."},
    {"topic":"DSA","difficulty":"Easy","question":"Count number of ways to cover a distance: Count ways to cover a distance using steps of 1, 2, or 3.","answer":"DP: ways[n] = ways[n-1] + ways[n-2] + ways[n-3]. Base: ways[0]=1, ways[1]=1, ways[2]=2. Similar to tribonacci. Time: O(n), Space: O(1) with three variables."},
    {"topic":"DSA","difficulty":"Easy","question":"Connect n ropes with minimum cost (already in Heap section): Minimize cost to connect ropes.","answer":"Use a min-heap. Repeatedly extract two shortest ropes, add their lengths to cost, push sum back. Time: O(n log n), Space: O(n). Greedy choice: always connecting the two shortest ropes is optimal."},
    {"topic":"DSA","difficulty":"Medium","question":"Largest Number in one Swap: Given an integer, find the largest number possible by swapping at most one pair of digits.","answer":"Traverse from right to left tracking the max digit seen. When a smaller digit is to the left of a larger one, mark the leftmost such pair for swap. Time: O(n), Space: O(n) for digit array. Edge case: leading zeros."},

    # === BIT MANIPULATIONS (3) ===
    {"topic":"DSA","difficulty":"Easy","question":"Counting Bits: Given an integer n, for each i from 0 to n, count the number of 1-bits in its binary representation.","answer":"DP: ans[i] = ans[i>>1] + (i & 1). Recurrence uses the fact that shifting right halves the number; the lost last bit determines the extra 1. Time: O(n), Space: O(n). Also known as popcount."},
    {"topic":"DSA","difficulty":"Easy","question":"Missing Number (1 to n range): Find the missing number in an array of n distinct numbers from 0 to n.","answer":"Use XOR: XOR all array elements with all numbers from 0 to n. The result is the missing number as duplicates cancel out. Time: O(n), Space: O(1). Alternative: sum formula n*(n+1)/2 - actual sum."},
    {"topic":"DSA","difficulty":"Medium","question":"Find XOR of all subsets of a set: Compute XOR of XORs of all subsets of an array.","answer":"If array size > 1, the result is 0 because each bit appears in 2^(n-1) subsets which is even. If size == 1, result is the element itself. Time: O(1) after checking size, Space: O(1)."},
]

def main():
    with open(QUESTIONS_JSON, 'r', encoding='utf-8') as f:
        existing = json.load(f)

    print(f"Existing questions: {len(existing)}")

    existing_texts = set()
    for q in existing:
        existing_texts.add(q['question'].lower().strip())

    next_id = max(q['id'] for q in existing) + 1 if existing else 1
    added = 0
    skipped = 0

    for q in questions:
        key = q['question'].lower().strip()
        if key not in existing_texts:
            existing_texts.add(key)
            q['id'] = next_id
            next_id += 1
            existing.append(q)
            added += 1
        else:
            skipped += 1

    with open(QUESTIONS_JSON, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)

    print(f"Added: {added}, Skipped (duplicates): {skipped}")
    print(f"Total: {len(existing)}")

    topics = {}
    for q in existing:
        topics[q['topic']] = topics.get(q['topic'], 0) + 1
    print("\n=== TOPIC COUNTS ===")
    for t, c in sorted(topics.items()):
        print(f"  {t}: {c}")

if __name__ == '__main__':
    main()
