#!/usr/bin/env python3
"""Add System Design Q&A from GFG LLD and HLD pages to questions.json."""
import json, os

QUESTIONS_JSON = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'questions.json')

questions = [
    # === LOW-LEVEL DESIGN (LLD) - 20 questions ===
    {"topic":"System Design","difficulty":"Medium","question":"What is the purpose of Low-Level System Design in software development?","answer":"Low-Level Design (LLD) serves as a detailed blueprint that bridges high-level architecture with implementation-ready modules. It defines internal logic of components, class structures, APIs, data flow, and interactions at a granular level. Key purposes: ensure the system is scalable, maintainable, and extensible; translate abstract architectural ideas into clear class/sequence diagrams; minimize ambiguity before coding; provide developers with a roadmap for implementation consistent with architectural goals."},
    {"topic":"System Design","difficulty":"Medium","question":"How does database indexing optimize query performance?","answer":"Database indexing improves query performance by creating auxiliary data structures (B-Trees, Hash Indexes, Bitmap Indexes) that allow faster lookups than full table scans. Benefits: speeds up SELECT queries via quick key-based access, reduces disk I/O by avoiding full scans, supports efficient range queries/joins/filtering. Trade-off: indexes require additional storage and slow down write operations (INSERT/UPDATE/DELETE), so careful index design is essential."},
    {"topic":"System Design","difficulty":"Medium","question":"What are the essential considerations in designing a schema for a relational database?","answer":"Key considerations: 1) Normalization - eliminate redundancy while balancing performance. 2) Constraints - use primary keys, foreign keys, unique, check constraints. 3) Indexes - create on frequently queried columns. 4) Relationships - define one-to-one, one-to-many, many-to-many correctly. 5) Data types - choose appropriate types to save space and optimize queries. 6) Scalability - consider sharding, partitioning, denormalization. 7) Security - access controls and encryption."},
    {"topic":"System Design","difficulty":"Medium","question":"Why is concurrency control important in multi-threaded systems?","answer":"Concurrency control ensures data integrity and system correctness when multiple threads access shared resources simultaneously. Without it, race conditions, deadlocks, or inconsistent states occur. Managed using: locks/mutexes for exclusive access, semaphores for limited resources, atomic operations for indivisible updates, read-write locks for multiple readers with few writers. This keeps systems predictable, safe, and efficient under parallel execution."},
    {"topic":"System Design","difficulty":"Medium","question":"What are UML Behavioral Diagrams?","answer":"UML Behavioral Diagrams capture dynamic aspects of a system, modeling how objects interact and change state in response to events. Types: Use Case Diagrams (actor-system interactions), Sequence Diagrams (object interactions in time sequence), Activity Diagrams (workflows/processes), State Machine Diagrams (object states and transitions), Communication Diagrams (message-based interactions). These are crucial in LLD for visualizing control flow and runtime behavior."},
    {"topic":"System Design","difficulty":"Medium","question":"How do you model a sequence diagram for a user login process in UML?","answer":"Actors/Objects: User, Login Controller, Authentication Service, Database. Flow: 1) User enters credentials -> sent to Login Controller. 2) Login Controller forwards to Authentication Service. 3) Authentication Service queries Database to validate. 4) Database responds with user record/failure. 5) Authentication Service returns success/failure to Login Controller. 6) Login Controller sends response to User. Objects are lifelines, messages are horizontal arrows, activation bars show method execution."},
    {"topic":"System Design","difficulty":"Medium","question":"How would you model the behavior of a system using a state diagram in UML?","answer":"A state diagram models how an object transitions between states in response to events. Notation: states as rounded rectangles, transitions as arrows labeled with events, initial state as filled circle, final state as double circle. Example (Payment System): States: Pending -> Processing -> Completed/Failed. Transitions: 'Payment Approved' leads Processing->Completed, 'Payment Failed' leads Processing->Failed. Useful for modeling lifecycles of sessions, orders, transactions."},
    {"topic":"System Design","difficulty":"Medium","question":"What factors influence the choice of appropriate data structures in Low-Level System Design?","answer":"Factors: 1) Access patterns - read-heavy favors hash maps for caching, write-heavy favors linked lists/queues. 2) Time complexity needs - fast lookups need hash tables, ordered access needs balanced trees/heaps. 3) Space complexity - memory constraints may require compact structures like arrays/bitsets. 4) Concurrency requirements - thread-safe structures like concurrent queues. 5) Scalability - distributed hash tables for large-scale systems. 6) Use case - graphs for social networks, tries for autocomplete."},
    {"topic":"System Design","difficulty":"Medium","question":"When designing a database schema, what are the benefits of normalization?","answer":"Benefits: eliminates redundancy by avoiding duplicate data, improves storage efficiency, enhances data integrity by reducing insert/update/delete anomalies, provides clearer relationships (each table represents a single entity), and simplifies maintenance (schema changes have minimal side effects). However, over-normalization increases join complexity, so it's often balanced with denormalization for performance."},
    {"topic":"System Design","difficulty":"Hard","question":"How do you design an efficient logging and monitoring system for a complex application?","answer":"Logging: use structured JSON format, set log levels (DEBUG, INFO, WARN, ERROR, FATAL), centralize collection (ELK Stack, Splunk, Fluentd), add correlation IDs to trace requests across microservices. Monitoring: collect system metrics (CPU, memory, latency), use time-series DBs (Prometheus, InfluxDB), implement dashboards (Grafana, Kibana). Alerting: configure threshold alerts and ML-based anomaly detection. Best practices: avoid excessive logging, separate app/security/audit logs, ensure compliance."},
    {"topic":"System Design","difficulty":"Easy","question":"What are Design Patterns?","answer":"Design patterns are general, reusable solutions to recurring problems in software design. They are templates/guidelines applied in different contexts, not code. They promote reusability, reduce design errors, and make systems more scalable and maintainable. Examples: Singleton (single instance for DB connection pool), Observer (one-to-many dependency for event-driven systems), Factory (delegates object creation logic)."},
    {"topic":"System Design","difficulty":"Medium","question":"Can you explain the Singleton Design Pattern and its use cases?","answer":"The Singleton Pattern ensures a class has only one instance with a global access point. Implemented via: private constructor, static instance variable, static getInstance() method. Use cases: database connection pools, configuration managers, logging services. Overuse can introduce global state making code harder to test and maintain."},
    {"topic":"System Design","difficulty":"Medium","question":"What is the Observer Design Pattern? How would you implement it?","answer":"The Observer Pattern establishes a one-to-many dependency between objects. When the subject (publisher) changes state, all observers (subscribers) are notified automatically. Key components: Subject (maintains observer list, notifies them) and Observers (subscribe and react). Real-world: GUI frameworks (button notifies click listeners), messaging systems (publisher->subscribers), stock trading (price change updates dashboards)."},
    {"topic":"System Design","difficulty":"Medium","question":"Describe the Factory Design Pattern and when you would use it.","answer":"The Factory Pattern provides an interface for creating objects but defers instantiation to subclasses or a centralized factory method. Benefits: encapsulates creation logic, promotes loose coupling, simplifies maintenance when adding new types. Use when: object type isn't known until runtime, working with a family of related objects, complex creation logic needs centralization. Example: ShapeFactory returns Circle/Square based on input type."},
    {"topic":"System Design","difficulty":"Medium","question":"What is the Strategy Design Pattern?","answer":"The Strategy Pattern is a behavioral pattern enabling algorithm selection at runtime. Instead of hardcoding multiple algorithms in one class, each algorithm is encapsulated in its own class with a common interface. Structure: Context (uses a strategy), Strategy Interface (common algorithm interface), Concrete Strategies (different implementations). Use cases: payment processing (Credit Card/UPI/PayPal), sorting algorithms (QuickSort/MergeSort/HeapSort), compression (ZIP/RAR/GZIP). Promotes Open/Closed Principle."},
    {"topic":"System Design","difficulty":"Hard","question":"How would you design a logging mechanism for troubleshooting and performance analysis in a distributed system?","answer":"Key aspects: 1) Structured logging (JSON) for machine readability with levels (DEBUG, INFO, WARN, ERROR, FATAL) and contextual metadata (request ID, service name, timestamp). 2) Centralized aggregation via ELK Stack, Splunk, or Fluentd. 3) Correlation IDs and distributed tracing (Jaeger, Zipkin, OpenTelemetry) to follow requests across microservices. 4) Performance monitoring for latency metrics, slow queries, error rates. 5) Anomaly detection and alerts for unusual patterns."},
    {"topic":"System Design","difficulty":"Hard","question":"Describe the factors influencing choice of algorithms when designing a sorting system for large datasets.","answer":"Key factors: 1) Data size - small datasets use in-memory (QuickSort/MergeSort), huge datasets need external sorting (External Merge Sort). 2) Time complexity - critical paths need O(n log n) algorithms. 3) Memory constraints - limited memory favors in-place (HeapSort/QuickSort). 4) Parallelization - distributed systems use Parallel MergeSort or MapReduce-based sorting (Hadoop/Spark). 5) Stability - if duplicate order matters, use stable algorithms (MergeSort/TimSort)."},
    {"topic":"System Design","difficulty":"Hard","question":"In Low-Level System Design, how do you handle versioning and backward compatibility in evolving software systems?","answer":"Best practices: 1) API versioning with versioned endpoints (/api/v1/users, /api/v2/users) and gradual deprecation. 2) Database schema evolution using migration tools (Liquibase, Flyway) with backward-compatible changes (avoid dropping columns immediately). 3) Feature toggles for gradual rollout. 4) Backward-compatible protocols with optional fields (Protobuf). 5) Comprehensive regression testing to ensure existing functionality works."},
    {"topic":"System Design","difficulty":"Hard","question":"How would you design a secure authentication and authorization system in a distributed application?","answer":"Authentication: token-based (OAuth 2.0, JWTs), password hashing with bcrypt/argon2 + salting, MFA (SMS/email/TOTP), SSO for centralized auth. Authorization: RBAC (roles like admin/user/guest), ABAC (context-based rules), fine-grained permissions at resource level. Distributed considerations: Identity Providers (Keycloak, Auth0, Okta), secure token exchange between microservices (validate JWTs), TLS/SSL for data-in-transit. Auditing: logs of login attempts and access denials, anomaly detection."},

    # === HIGH-LEVEL DESIGN (HLD) - 24 questions ===
    {"topic":"System Design","difficulty":"Medium","question":"What are the key components of a High-Level Design (HLD)?","answer":"HLD defines overall system architecture with a bird's-eye view. Key components: System Architecture (major layers like UI, API, DB), Components (Authentication Service, Payment Service, Database Layer), Technology Stack (languages, frameworks, DB, infrastructure), Scalability Considerations (caching, partitioning, replication), Security Mechanisms (authentication, authorization, encryption, auditing), and Integration Points (external services, third-party APIs)."},
    {"topic":"System Design","difficulty":"Medium","question":"How do you decide between a Monolithic and Microservices Architecture in HLD?","answer":"Monolithic: simple to develop/deploy/test, poor scalability, tightly coupled. Best for small apps, startups, MVPs, small teams. Microservices: independent scaling, tech flexibility, fault isolation, complex deployment. Best for large-scale systems, distributed teams, high scalability needs. Rule of thumb: start monolithic if small, refactor to microservices as the system grows."},
    {"topic":"System Design","difficulty":"Medium","question":"What are the trade-offs between a Relational and Non-Relational (NoSQL) database in an HLD?","answer":"Relational (RDBMS): structured schema, ACID transactions, strong consistency, complex queries via SQL joins, vertical scaling. Best for banking, ERP, inventory management. NoSQL: flexible schema, horizontal scaling, high availability, fast read/write, eventual consistency. Types: Key-Value, Document, Column, Graph. Best for real-time apps, big data, social media, IoT. Choose RDBMS for consistency and structured data; NoSQL for scalability and unstructured data."},
    {"topic":"System Design","difficulty":"Medium","question":"How do you ensure high availability in an HLD?","answer":"Strategies: 1) Redundancy - replicate critical components (servers, DB replicas). 2) Load Balancing - distribute requests across nodes. 3) Failover Mechanisms - automatic switch to backup systems. 4) Geo-distributed Deployment - deploy across regions/zones. 5) Disaster Recovery Plan - backup and restore strategies. 6) Monitoring and Alerts - detect failures quickly."},
    {"topic":"System Design","difficulty":"Easy","question":"Explain the concept of load balancing in the context of HLD.","answer":"Load balancing distributes incoming requests across multiple servers for efficient resource utilization, improved performance (lower response times), and high availability (no single point of failure). Techniques: Round Robin (sequential assignment), Least Connections (route to server with fewest connections), Weighted Distribution (based on server capacity), Geo Load Balancing (route based on user location). Examples: Nginx, HAProxy, AWS ELB, GCP Load Balancer."},
    {"topic":"System Design","difficulty":"Medium","question":"What are the key considerations for designing a scalable system in HLD?","answer":"Considerations: 1) Horizontal Scaling - add more servers with stateless services. 2) Vertical Scaling - upgrade hardware (limited). 3) Partitioning/Sharding - split large datasets across nodes. 4) Caching - reduce DB load with in-memory stores (Redis, Memcached). 5) Asynchronous Processing - use queues (Kafka, RabbitMQ). 6) Database Replication - read replicas for heavy reads. 7) CDN - cache static content closer to users."},
    {"topic":"System Design","difficulty":"Medium","question":"How do you handle security concerns in HLD?","answer":"Key measures: 1) Authentication/Authorization - RBAC/ABAC, OAuth2.0, JWT. 2) Encryption - TLS/HTTPS in transit, AES/KMS at rest. 3) Input Validation - prevent SQL injection, XSS. 4) Secure APIs - API gateways, rate limiting, request validation. 5) Regular patching. 6) Monitoring/logging for suspicious activity. 7) Zero-Trust principles - never trust, always verify, least privilege access."},
    {"topic":"System Design","difficulty":"Easy","question":"Explain the concept of caching in HLD and its benefits.","answer":"Caching stores frequently accessed data in a fast-access layer (in-memory) to reduce repeated backend/database calls. Types: client-side caching, CDN, server-side (Redis, Memcached), application-level caching. Benefits: reduces response time (faster reads), lowers database load, improves scalability by serving repeated requests from cache, enhances user experience with low-latency responses."},
    {"topic":"System Design","difficulty":"Medium","question":"What are the steps involved in designing an API in HLD?","answer":"Steps: 1) Identify resources and use cases. 2) Define endpoints (REST: /users/{id}, /orders; GraphQL schema). 3) Specify request/response formats (JSON/XML). 4) Authentication/Authorization (OAuth 2.0, JWT, API keys). 5) Error handling and status codes (404, 500). 6) Versioning strategy (/v1, /v2). 7) Rate limiting and throttling. 8) Documentation (Swagger/OpenAPI)."},
    {"topic":"System Design","difficulty":"Medium","question":"How do you ensure data consistency across distributed systems in HLD?","answer":"Consistency models: Strong, Eventual, or Causal (choose based on needs). Techniques: distributed transactions (2PC/3PC) for atomic operations, idempotent operations for safe retries, conflict resolution policies (last write wins, vector clocks, CRDTs). Use eventual consistency for high availability, strong consistency for critical paths. Trade-off is between availability and consistency as per CAP theorem."},
    {"topic":"System Design","difficulty":"Medium","question":"What role does fault tolerance play in HLD?","answer":"Fault tolerance ensures the system continues operating even when components fail. Techniques: redundancy (replicating servers/databases), replication (data copies across nodes/regions), graceful degradation (disable non-critical features during failures), failure isolation (microservices, circuit breakers). Importance: improves reliability, minimizes downtime, ensures user trust."},
    {"topic":"System Design","difficulty":"Hard","question":"How do you design for disaster recovery in HLD?","answer":"Key elements: 1) Backups - regular, automated, tested restores. 2) Geo-replication - data mirrored across regions/data centers. 3) Failover mechanisms - automatic switch to standby servers/clusters. 4) Defined RPO (Recovery Point Objective) and RTO (Recovery Time Objective). 5) DR Drills - regularly test recovery plans for effectiveness."},
    {"topic":"System Design","difficulty":"Medium","question":"Explain the concept of Event-Driven Architecture in HLD.","answer":"EDA is a loosely coupled architecture where components communicate via events instead of direct calls. Flow: Producer -> Event Bus (Kafka, RabbitMQ) -> Consumers. Benefits: asynchronous communication, high scalability and resilience, decoupled components (independent evolution). Use cases: real-time analytics, IoT systems, order processing pipelines."},
    {"topic":"System Design","difficulty":"Hard","question":"What are the key considerations for designing a logging and monitoring system in HLD?","answer":"Logging: structured JSON logs, levels (INFO, WARN, ERROR, DEBUG), contextual info (trace IDs, request IDs), centralized aggregation (ELK stack, Splunk). Monitoring: metrics (CPU, memory, latency, error rates), dashboards (Grafana, Prometheus), alerts (threshold-based, anomaly detection). Considerations: scalability of log storage, correlation between logs/metrics, real-time alerting, compliance with audit log requirements."},
    {"topic":"System Design","difficulty":"Medium","question":"How do you handle concurrency control in HLD?","answer":"Concurrency control ensures data consistency when multiple users/processes access the same resource. Techniques: locks (row/record-level, optimistic/pessimistic), Multi-Version Concurrency Control (MVCC), isolation levels (Read Committed, Repeatable Read, Serializable). Design choice: read-heavy systems use MVCC; strict financial transactions use locking with higher isolation. Ensures no lost updates, dirty reads, or inconsistent states."},
    {"topic":"System Design","difficulty":"Medium","question":"What are the principles of RESTful API design in HLD?","answer":"Principles: use HTTP methods properly (GET, POST, PUT, DELETE), resource-based URIs (/users/{id}), statelessness (no session state on server), standard status codes (200 OK, 404 Not Found, 500 Error), content negotiation (JSON/XML via headers), versioning (/api/v1/) for backward compatibility."},
    {"topic":"System Design","difficulty":"Medium","question":"Explain the role of a message broker in HLD and give examples.","answer":"A message broker decouples services and enables asynchronous communication. Roles: message routing, buffering, delivery guarantees, scaling event-driven systems. Examples: Kafka (stream processing, high throughput), RabbitMQ (task queues, reliability), Amazon SQS (cloud-native queue). Benefits: loose coupling, fault isolation, better scalability, resilience."},
    {"topic":"System Design","difficulty":"Easy","question":"How does a Content Delivery Network (CDN) achieve both high availability and low latency?","answer":"Low latency: CDN caches content at edge servers near users, reducing round-trip time. High availability: distributed servers, automatic failover, and load balancing ensure uptime even if some nodes fail. CDNs use replication, Anycast routing, and intelligent caching strategies to achieve both goals."},
    {"topic":"System Design","difficulty":"Hard","question":"What are the considerations for designing a fault-tolerant network infrastructure in HLD?","answer":"Considerations: 1) Redundancy - multiple network paths and backup servers. 2) Isolation - segment critical services to limit blast radius. 3) Dynamic routing protocols (BGP/OSPF) for rerouting traffic. 4) Load balancing for even request distribution. 5) Security - firewalls, intrusion detection. 6) Disaster Recovery - hot/warm DR sites for continuity."},
    {"topic":"System Design","difficulty":"Medium","question":"What role does containerization play in HLD and how does it benefit system architecture?","answer":"Containerization packages apps and dependencies into isolated containers (Docker). Benefits: consistency across environments, horizontal scalability with orchestration (Kubernetes), resource efficiency (lighter than VMs), supports microservices (each service isolated but easy to deploy), resilience (failure in one container doesn't crash others)."},
    {"topic":"System Design","difficulty":"Hard","question":"How do you design for data privacy and protection in HLD?","answer":"Approach: 1) Encryption - data at rest (AES), data in transit (TLS/SSL). 2) Access control - RBAC/ABAC with least privilege. 3) Data anonymization - masking PII. 4) Compliance - GDPR, HIPAA adherence. 5) Auditing and monitoring - track data access. 6) Regular security reviews - penetration testing, vulnerability scanning."},
    {"topic":"System Design","difficulty":"Medium","question":"Explain the concept of a distributed cache in HLD and its advantages.","answer":"A distributed cache stores frequently accessed data across multiple nodes in a distributed environment. Advantages: faster response (reduces DB calls), scalability (horizontal distribution), fault tolerance (replicated cache), handles high read loads efficiently. Popular solutions: Redis Cluster, Memcached, Hazelcast."},
    {"topic":"System Design","difficulty":"Medium","question":"How do you ensure data integrity in an HLD?","answer":"Techniques: database constraints (primary key, foreign key, unique, not null), input validation at API and DB layers, transactions enforcing ACID properties, checksums/hashing for data verification during transmission, error handling with retry and logging for inconsistencies, and encryption to protect data integrity and confidentiality."},
    {"topic":"System Design","difficulty":"Medium","question":"How does the CAP theorem affect the design of a distributed database?","answer":"CAP theorem states a distributed system can guarantee only 2 of 3: Consistency (all nodes see same data), Availability (system responds despite failures), Partition Tolerance (works despite network splits). Impact: CP systems (MongoDB, HBase) prioritize consistency over availability. AP systems (Cassandra, DynamoDB) prioritize availability over consistency. Choice depends on application: banking (CP) vs social media feeds (AP)."},
]

def main():
    with open(QUESTIONS_JSON, 'r', encoding='utf-8') as f:
        existing = json.load(f)

    print(f"Existing questions: {len(existing)}")

    existing_texts = set()
    for q in existing:
        existing_texts.add(q['question'].lower().strip())

    next_id = max(q['id'] for q in existing) + 1 if existing else 1
    added = 0
    skipped = 0

    for q in questions:
        key = q['question'].lower().strip()
        if key not in existing_texts:
            existing_texts.add(key)
            q['id'] = next_id
            next_id += 1
            existing.append(q)
            added += 1
        else:
            skipped += 1

    with open(QUESTIONS_JSON, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)

    print(f"Added: {added}, Skipped (duplicates): {skipped}")
    print(f"Total: {len(existing)}")

    topics = {}
    for q in existing:
        topics[q['topic']] = topics.get(q['topic'], 0) + 1
    print("\n=== TOPIC COUNTS ===")
    for t, c in sorted(topics.items()):
        print(f"  {t}: {c}")

if __name__ == '__main__':
    main()
