#!/usr/bin/env python3
"""Add Puzzles from GFG page to questions.json."""
import json, os

QUESTIONS_JSON = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'questions.json')

questions = [
    # === TOP 10 MOST ASKED PUZZLES ===
    {"topic":"Puzzles","difficulty":"Medium","question":"The Burning Ropes: You have two ropes that each take exactly 60 minutes to burn, but they burn unevenly. How do you measure exactly 45 minutes?","answer":"Light rope A at both ends and rope B at one end simultaneously. Rope A will burn completely in 30 minutes. At that point, light the second end of rope B. Rope B had 30 minutes of burn time left and lighting both ends makes it burn in 15 minutes. Total: 30 + 15 = 45 minutes."},
    {"topic":"Puzzles","difficulty":"Hard","question":"25 Horses Puzzle: Find the top 3 fastest horses among 25 using only a 5-lane track (no timer). What's the minimum number of races needed?","answer":"7 races. Step 1: Run 5 heats of 5 horses each (5 races). Step 2: Race the winners of each heat (6th race) to find fastest overall. Step 3: The 2nd and 3rd place from the fastest horse's heat, plus 2nd place from the 2nd fastest horse's heat, plus 3rd place from the 2nd fastest's heat, plus the 2nd place from the 6th race - race these 5 (7th race). Top 2 from this race plus the 6th race winner are the top 3."},
    {"topic":"Puzzles","difficulty":"Medium","question":"Bridge Crossing Problem (Torch and Bridge): Four people need to cross a bridge at night with one torch. They take 1, 2, 5, and 10 minutes respectively. At most two can cross at a time. What's the minimum total time?","answer":"17 minutes. 1) 1 and 2 cross (2 min), 1 returns (1 min) -> total 3. 2) 5 and 10 cross (10 min), 2 returns (2 min) -> total 15. 3) 1 and 2 cross (2 min) -> total 17. The key insight is that the two slowest cross together to avoid 5+10+10=25."},
    {"topic":"Puzzles","difficulty":"Medium","question":"Poison and Rat: You have 1000 bottles of wine, one is poisoned. A rat dies within 24 hours of drinking poison. What's the minimum number of rats needed to find the poisoned bottle in 24 hours?","answer":"10 rats. Number the bottles 0-999 (10-bit binary). Each rat represents one bit. Feed rat i a mixture from all bottles where bit i is 1. After 24 hours, the pattern of dead rats gives the binary number of the poisoned bottle. 2^10 = 1024 > 1000, so 10 rats suffice."},
    {"topic":"Puzzles","difficulty":"Medium","question":"Two-Egg Problem (Egg Dropping): You have 2 identical eggs and a 100-floor building. Find the highest floor from which eggs can be dropped without breaking, with minimum drops.","answer":"14 drops. Drop the first egg from floors 14, 27, 39, 50, 60, 69, 77, 84, 90, 95, 99 (decrease by 1 each time: 14+13+12+...+1 = 105 > 100). When the first egg breaks, you have at most the remaining number of drops to test with the second egg linearly. This minimizes the worst-case number of drops."},
    {"topic":"Puzzles","difficulty":"Easy","question":"Water Jug Problem (Four Gallon Problem): You have a 3-gallon jug and a 5-gallon jug. How do you measure exactly 4 gallons?","answer":"1) Fill the 5-gallon jug. 2) Pour from 5 into 3 until 3 is full -> 2 left in 5. 3) Empty the 3-gallon jug. 4) Pour the 2 gallons from 5 into 3. 5) Fill the 5-gallon jug again. 6) Pour from 5 into 3 until 3 is full (takes 1 gallon). 7) Exactly 4 gallons remain in the 5-gallon jug."},
    {"topic":"Puzzles","difficulty":"Easy","question":"Number of Legs in the Palace: In a palace with 7 rooms, each room has 7 cats, each cat has 7 kittens, each kitten has 7 mice. How many legs are there?","answer":"7 rooms * 7 cats = 49 cats. 49 cats * 7 kittens = 343 kittens. 343 kittens * 7 mice = 2401 mice. Total creatures: 49 + 343 + 2401 = 2793 four-legged creatures. 2793 * 4 = 11,172 legs. The rooms don't add legs."},
    {"topic":"Puzzles","difficulty":"Easy","question":"8 Ball Problem: You have 8 balls, one is heavier than the others. Using a balance scale, find the heavier ball in minimum weighings.","answer":"2 weighings. 1) Put 3 balls on each side. If they balance, the heavy ball is among the 2 left out -> weigh those 2. If one side is heavier, the heavy ball is among those 3. 2) From the heavier group of 3, weigh 1 vs 1. If they balance, the third is heavy. If one is heavier, that's the answer."},
    {"topic":"Puzzles","difficulty":"Medium","question":"100 Prisoners with Red/Black Hats: 100 prisoners are lined up, each wearing a red or black hat. Each sees all hats in front but not their own. Starting from the back, each must guess their own hat color. If at least 99 are correct, they all go free. What strategy guarantees this?","answer":"The prisoner at the back (who sees 99 hats) says 'red' if the number of red hats he sees is even, 'black' if odd. This is the parity signal. The next prisoner sees 98 hats and knows the parity of all 99 (from the first guess), so he can deduce his own color. Each subsequent prisoner knows the parity of hats behind and counts hats in front to deduce their own. 99th prisoner is guaranteed correct, the first has 50% chance."},
    {"topic":"Puzzles","difficulty":"Medium","question":"Cheryl's Birthday: Cheryl tells Albert the month and Bernard the day of her birthday. Albert: 'I don't know, and Bernard doesn't know either.' Bernard: 'Now I know.' Albert: 'Now I know too.' The possible dates are May 15/16/19, June 17/18, July 14/16, August 14/15/17. When is Cheryl's birthday?","answer":"July 16. Step 1: Albert knows month and says Bernard doesn't know. This eliminates May and June (which have unique days 18 and 19). Step 2: Bernard now knows. The remaining dates are July 14/16, August 14/15/17. If Bernard's day were 14 (which appears in both months), he wouldn't know. So 14 is eliminated, leaving July 16, Aug 15, Aug 17. Step 3: Albert now knows too - if his month were August (two options), he wouldn't know. So it must be July, and the date is July 16."},

    # === ANALYTICAL/MATHEMATICAL PUZZLES ===
    {"topic":"Puzzles","difficulty":"Medium","question":"Find ages of daughters: A mathematician says 'I have 3 daughters. The product of their ages is 36. The sum equals my house number.' The visitor says he needs more info. The mathematician says 'The oldest has blue eyes.' What are the ages?","answer":"9, 2, 2. The possible triplets that multiply to 36: (1,1,36) sum=38, (1,2,18)=21, (1,3,12)=16, (1,4,9)=14, (1,6,6)=13, (2,2,9)=13, (2,3,6)=11, (3,3,4)=10. The visitor said he still needs info after knowing the sum, meaning the sum wasn't unique - only 13 appears twice (1,6,6) and (2,2,9). 'The oldest has blue eyes' indicates there IS an oldest, so (1,6,6) is eliminated (twins as oldest). Answer: 9, 2, 2."},
    {"topic":"Puzzles","difficulty":"Medium","question":"Monty Hall Problem: You're on a game show with 3 doors. One hides a car, two hide goats. You pick a door. The host (who knows what's behind each door) opens another door revealing a goat. Should you switch to the remaining door?","answer":"Yes, switching gives a 2/3 chance of winning, sticking gives 1/3. Initially your chance is 1/3. The host always opens a door with a goat. If you initially picked a goat (2/3 probability), switching wins. If you initially picked the car (1/3), switching loses. So switching wins 2/3 of the time."},
    {"topic":"Puzzles","difficulty":"Easy","question":"Camel and Banana Puzzle: A camel must transport 3000 bananas across 1000 km. It can carry at most 1000 bananas at once and eats 1 banana per km. What's the maximum number of bananas that can reach the destination?","answer":"533 bananas. Strategy: move in stages. The camel needs to make multiple trips to move bananas forward. Optimal: move 1000 bananas 200 km forward using 3 trips forward + 2 back = 1000 - (5*200) = 0 at first cache. Then 1000 bananas 334 km forward using 2 trips forward + 1 back = 1000 - (3*334) = -2 (so 333 km). Final 1000 bananas go 467 km straight = 533 remaining."},
    {"topic":"Puzzles","difficulty":"Medium","question":"Calculate total distance traveled by bee: Two trains approach each other at 30 km/h each from 60 km apart. A bee flies back and forth between them at 50 km/h until they collide. How far does the bee travel?","answer":"50 km. The relative speed of the trains is 60 km/h. Time until collision = 60/60 = 1 hour. The bee flies at 50 km/h for 1 hour, so distance = 50 km. The trick is to not sum infinite series - just multiply speed by time."},
    {"topic":"Puzzles","difficulty":"Easy","question":"3 Ants and Triangle: Three ants are at the corners of a triangle. Each starts moving along an edge toward another corner randomly. What's the probability they never collide?","answer":"1/4 (25%). Each ant can choose 2 directions (clockwise or counter-clockwise). Total = 2^3 = 8 possibilities. They never collide only if all 3 go clockwise (1 way) or all 3 go counter-clockwise (1 way). So 2/8 = 1/4."},
    {"topic":"Puzzles","difficulty":"Easy","question":"Find the Jar with contaminated pills: You have 5 jars of pills. One jar has contaminated pills that weigh 9g instead of 10g. Using a digital scale just once, find the contaminated jar.","answer":"Take 1 pill from jar 1, 2 from jar 2, 3 from jar 3, 4 from jar 4, 5 from jar 5. Total expected weight if all normal = (1+2+3+4+5)*10 = 150g. If jar 1 is contaminated, weight = 149g. If jar 2, weight = 148g. If jar k is contaminated, weight = 150-k. One weighing suffices."},
    {"topic":"Puzzles","difficulty":"Medium","question":"Strategy for a 2-Player Coin Game: Two players take turns removing 1, 2, or 3 coins from a pile of 21. The player who takes the last coin wins. What's the winning strategy?","answer":"Go first and take 1 coin, then always make the sum with opponent's move equal 4 (if opponent takes 2, you take 2; if they take 3, you take 1; if they take 1, you take 3). This ensures you get the 1st, 5th, 9th, 13th, 17th, 21st coins. The winning positions are multiples of 4."},
    {"topic":"Puzzles","difficulty":"Hard","question":"5 Pirates and 100 Gold Coins: 5 pirates (ranked 1-5) divide 100 gold coins. The senior pirate proposes a distribution. If at least half (including himself) vote yes, it passes. Otherwise he's killed and the next senior proposes. Assuming pirates are perfectly logical, greedy, and bloodthirsty, what does the senior pirate propose?","answer":"Pirate 5 proposes: 98 for himself, 0 for pirates 4 and 3, 1 for pirate 2, 1 for pirate 1. Reasoning: Pirate 5 needs 3 votes (including his own). If he dies, pirate 4 would propose and need 2 votes. Pirate 4's optimal: 99 for self, 0 for 3, 1 for 2, 0 for 1. So pirate 3 would get 0 in that scenario. Pirate 5 offers pirate 3 nothing (still votes yes because 0 is same as what he'd get). Pirate 2 gets 0 if pirate 4 proposes, so pirate 5 offers him 1. Pirate 1 gets nothing from pirate 4, so pirate 5 offers him 1."},
    {"topic":"Puzzles","difficulty":"Easy","question":"3 Bulbs and 3 Switches: You're in a room with 3 switches controlling 3 bulbs in another room. You can flip switches any way you want, then enter the other room once. How do you determine which switch controls which bulb?","answer":"Turn switch 1 ON and wait 5 minutes, then turn it OFF. Turn switch 2 ON. Leave switch 3 OFF. Enter the room: the ON bulb is switch 2. The OFF bulbs - touch them: the warm bulb is switch 1, the cold bulb is switch 3. This uses the fact that an incandescent bulb retains heat."},
    {"topic":"Puzzles","difficulty":"Easy","question":"Farmer, Goat, Wolf, and Cabbage: A farmer needs to cross a river with a goat, wolf, and cabbage. His boat can carry only him and one item. He can't leave the goat with the wolf (eats it) or the goat with the cabbage (eats it). How?","answer":"1) Take goat across, return alone. 2) Take wolf across, bring goat back. 3) Take cabbage across, return alone. 4) Take goat across. Now all are across. The key is using the goat as the intermediary - it's the problematic item that conflicts with both others."},
    {"topic":"Puzzles","difficulty":"Easy","question":"Heaven and Hell Puzzle: You reach a fork in the road with two guards. One always lies, one always tells the truth. One path leads to Heaven, the other to Hell. You can ask one guard one question. What do you ask?","answer":"Ask either guard: 'If I asked the other guard which path leads to Heaven, what would they say?' Then take the opposite path. The liar would lie about what the truth-teller would say, and the truth-teller would truthfully report what the liar would say (which is a lie). Both will point to Hell. So take the other path."},
    {"topic":"Puzzles","difficulty":"Medium","question":"10 Coins Puzzle (Blindfolded): You're blindfolded with 10 coins, 3 heads up and 7 tails up. You need to split them into two groups with the same number of heads in each. How?","answer":"Split into any 3 coins and 7 coins. Flip all coins in the group of 3. Let's say the group of 3 has H heads initially. After flipping, it has 3-H heads. The remaining group of 7 has 3-H heads (since total heads = 3). Both groups have 3-H heads. Flipping equalizes the count."},
    {"topic":"Puzzles","difficulty":"Medium","question":"Egg Dropping Puzzle with 2 Eggs and K Floors: Generalize the two-egg problem for K floors. What's the minimum number of drops needed?","answer":"The minimum number of drops in worst case is ceil((sqrt(8K+1)-1)/2). For 100 floors, this gives 14. The strategy: first drop from floor x, then x+(x-1), then x+(x-1)+(x-2), etc. The sum of integers 1+2+...+n must be >= K, so n(n+1)/2 >= K. Solve: n >= ceil((sqrt(8K+1)-1)/2)."},
    {"topic":"Puzzles","difficulty":"Easy","question":"Measuring 6L water from 4L and 9L buckets: Using only a 4L and 9L bucket, measure exactly 6 liters of water.","answer":"1) Fill 9L. 2) Pour 9L into 4L until full -> 5L left in 9L. 3) Empty 4L. 4) Pour 5L from 9L into 4L -> 1L left in 9L. 5) Empty 4L. 6) Pour 1L from 9L into 4L. 7) Fill 9L. 8) Pour 9L into 4L (which has 1L) until full -> takes 3L, leaving 6L in 9L."},
    {"topic":"Puzzles","difficulty":"Medium","question":"25 Horses (Revised): Find the top 3 fastest horses among 25 using a 5-lane track. Minimum races?","answer":"7 races. 1) 5 initial heats (5 races). 2) Race the 5 winners (6th race) to rank heats. The 4th and 5th place horses and their entire heats are eliminated. 3) The 7th race: 2nd and 3rd from fastest heat, 1st and 2nd from second fastest heat, 1st from third fastest heat. Top 2 from this race plus the overall winner from race 6 are the top 3."},
    {"topic":"Puzzles","difficulty":"Medium","question":"Mislabeled Jars: Three jars are mislabeled 'Apples', 'Oranges', and 'Apples & Oranges'. Each jar contains either only apples, only oranges, or a mix. You can pick one fruit from one jar without looking. Determine the correct labels.","answer":"Pick a fruit from the jar labeled 'Apples & Oranges'. Since all labels are wrong, this jar must contain either only apples or only oranges. If you pick an apple, this jar is Apples. Then the jar labeled 'Oranges' can't be Oranges (wrong label) and can't be Apples (already found), so it must be Apples & Oranges. The last jar is Oranges. Same logic reversed if you pick an orange."},
]

def main():
    with open(QUESTIONS_JSON, 'r', encoding='utf-8') as f:
        existing = json.load(f)

    print(f"Existing questions: {len(existing)}")

    existing_texts = set()
    for q in existing:
        existing_texts.add(q['question'].lower().strip())

    next_id = max(q['id'] for q in existing) + 1 if existing else 1
    added = 0
    skipped = 0

    for q in questions:
        key = q['question'].lower().strip()
        if key not in existing_texts:
            existing_texts.add(key)
            q['id'] = next_id
            next_id += 1
            existing.append(q)
            added += 1
        else:
            skipped += 1

    with open(QUESTIONS_JSON, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)

    print(f"Added: {added}, Skipped (duplicates): {skipped}")
    print(f"Total: {len(existing)}")

    topics = {}
    for q in existing:
        topics[q['topic']] = topics.get(q['topic'], 0) + 1
    print("\n=== TOPIC COUNTS ===")
    for t, c in sorted(topics.items()):
        print(f"  {t}: {c}")

if __name__ == '__main__':
    main()
